import type { ArtisanCardData } from "@/components/landing/artisan-preview-card";

export const previewArtisans = [
  {
    id: "art-001",
    name: "Peter Mwangi",
    profession: "Plumber",
    profileImage: null,
    portfolioThumbnail: null,
    location: { city: "Kilimani", county: "Nairobi" },
    hourlyRate: 1800,
    isAvailable: true,
    isVerified: true,
    isPremium: false,
    rating: { average: 4.9, total: 82 },
    specializations: [
      { name: "Leak repair" },
      { name: "Pipe fitting" },
      { name: "Drainage" },
    ],
    gradient: "linear-gradient(135deg, #ecfdf5 0%, #a7f3d0 45%, #047857 100%)",
  },
  {
    id: "art-002",
    name: "Grace Wanjiku",
    profession: "Carpenter",
    profileImage: null,
    portfolioThumbnail: null,
    location: { city: "Kikuyu", county: "Kiambu" },
    hourlyRate: 2600,
    isAvailable: false,
    isVerified: true,
    isPremium: true,
    rating: { average: 4.8, total: 64 },
    specializations: [
      { name: "Cabinets" },
      { name: "Custom beds" },
      { name: "Shelving" },
    ],
    gradient: "linear-gradient(135deg, #f4f1e8 0%, #b89565 44%, #4b3524 100%)",
  },
  {
    id: "art-003",
    name: "Amina Hassan",
    profession: "Painter",
    profileImage: null,
    portfolioThumbnail: null,
    location: { city: "Westlands", county: "Nairobi" },
    hourlyRate: 1500,
    isAvailable: true,
    isVerified: true,
    isPremium: true,
    rating: { average: 4.9, total: 51 },
    specializations: [
      { name: "Wall prep" },
      { name: "Texture finish" },
      { name: "Repainting" },
    ],
    gradient: "linear-gradient(135deg, #fef3c7 0%, #fbbf24 44%, #065f46 100%)",
  },
  {
    id: "art-004",
    name: "Brian Otieno",
    profession: "Electrician",
    profileImage: null,
    portfolioThumbnail: null,
    location: { city: "Rongai", county: "Kajiado" },
    hourlyRate: 2200,
    isAvailable: true,
    isVerified: true,
    isPremium: false,
    rating: { average: 4.7, total: 73 },
    specializations: [
      { name: "Fault tracing" },
      { name: "Sockets" },
      { name: "Lighting" },
    ],
    gradient: "linear-gradient(135deg, #eef2ff 0%, #a7f3d0 46%, #064e3b 100%)",
  },
  {
    id: "art-005",
    name: "Daniel Kariuki",
    profession: "Mason",
    profileImage: null,
    portfolioThumbnail: null,
    location: { city: "Thika", county: "Kiambu" },
    hourlyRate: 2400,
    isAvailable: false,
    isVerified: true,
    isPremium: true,
    rating: { average: 4.8, total: 39 },
    specializations: [
      { name: "Tiling" },
      { name: "Waterproofing" },
      { name: "Grouting" },
    ],
    gradient: "linear-gradient(135deg, #f7fee7 0%, #86efac 45%, #166534 100%)",
  },
  {
    id: "art-006",
    name: "Joseph Njoroge",
    profession: "Welder",
    profileImage: null,
    portfolioThumbnail: null,
    location: { city: "Industrial Area", county: "Nairobi" },
    hourlyRate: 3000,
    isAvailable: true,
    isVerified: true,
    isPremium: false,
    rating: { average: 4.9, total: 91 },
    specializations: [
      { name: "Gates" },
      { name: "Grills" },
      { name: "Railings" },
    ],
    gradient: "linear-gradient(135deg, #f8fafc 0%, #cbd5e1 45%, #065f46 100%)",
  },
  {
    id: "art-007",
    name: "Mercy Achieng",
    profession: "Cleaner",
    profileImage: null,
    portfolioThumbnail: null,
    location: { city: "Nyali", county: "Mombasa" },
    hourlyRate: 1200,
    isAvailable: true,
    isVerified: false,
    isPremium: false,
    rating: { average: 4.6, total: 28 },
    specializations: [
      { name: "Deep cleaning" },
      { name: "Sofa care" },
      { name: "Carpets" },
    ],
    gradient: "linear-gradient(135deg, #ecfeff 0%, #99f6e4 44%, #0f766e 100%)",
  },
  {
    id: "art-008",
    name: "Samuel Kiptoo",
    profession: "Handyman",
    profileImage: null,
    portfolioThumbnail: null,
    location: { city: "Nakuru", county: "Nakuru" },
    hourlyRate: 1000,
    isAvailable: true,
    isVerified: true,
    isPremium: false,
    rating: { average: 4.7, total: 34 },
    specializations: [
      { name: "Mounting" },
      { name: "Locks" },
      { name: "Small fixes" },
    ],
    gradient: "linear-gradient(135deg, #f0fdf4 0%, #bbf7d0 44%, #15803d 100%)",
  },
] satisfies ArtisanCardData[];
