"use client";

import { Bookmark, ClipboardList, MessageCircle, Search, Settings, Star } from "lucide-react";

import { SimpleDashboardView } from "@/components/dashboard2/shared/simple-dashboard-view";

export function ClientOverviewView() {
  return <SimpleDashboardView eyebrow="Home" title="Find and manage trusted work" body="Track requests, messages, saved artisans, and reviews from one focused client workspace." actions={[{ label: "Find artisans", href: "/client-dashboard/find-artisans" }]} stats={[{ label: "Open jobs", value: 0, subtext: "In progress", icon: ClipboardList }, { label: "Saved", value: 0, subtext: "Artisans", icon: Bookmark }, { label: "Messages", value: 0, subtext: "Unread", icon: MessageCircle }]} items={[["Create a request", "Describe the work and choose an artisan to message."], ["Compare profiles", "Use verified badges, portfolios, ratings, and rates."], ["Leave reviews", "Help the best artisans build trust." ]].map(([title, body]) => ({ title, body }))} />;
}
export function ClientFindView() { return <SimpleDashboardView eyebrow="Search" title="Find artisans" body="Search by craft, county, rating, rate, availability, and specialization." actions={[{ label: "Browse public directory", href: "/artisans" }]} stats={[{ label: "Verified artisans", value: "Live", subtext: "Public directory", icon: Search }]} items={[["Search", "Find available artisans across Kenya."], ["Filter", "Narrow by skill, county, rating, and budget."], ["Message", "Start conversations before requesting work." ]].map(([title, body]) => ({ title, body }))} />; }
export function ClientSavedView() { return <SimpleDashboardView eyebrow="Shortlist" title="Saved artisans" body="Keep your favorite artisans in one place for future projects." stats={[{ label: "Saved", value: 0, subtext: "Profiles", icon: Bookmark }]} items={[["Favorites", "Return to trusted profiles quickly."], ["Compare", "Review rates, ratings, and portfolios side-by-side."], ["Contact", "Message saved artisans when you are ready." ]].map(([title, body]) => ({ title, body }))} />; }
export function ClientJobsView() { return <SimpleDashboardView eyebrow="Requests" title="Jobs" body="Track requests, quotes, active work, completed jobs, and reviews." stats={[{ label: "Active", value: 0, subtext: "Jobs", icon: ClipboardList }, { label: "Pending reviews", value: 0, subtext: "To submit", icon: Star }]} items={[["Requested", "Jobs waiting for quotes."], ["Accepted", "Work that is scheduled or underway."], ["Completed", "Finished jobs ready for review." ]].map(([title, body]) => ({ title, body }))} />; }
export function ClientMessagesView() { return <SimpleDashboardView eyebrow="Inbox" title="Messages" body="Discuss project details, attachments, quotes, and next steps with artisans." stats={[{ label: "Unread", value: 0, subtext: "Messages", icon: MessageCircle }]} items={[["Threads", "Every conversation stays connected to a job."], ["Scope", "Confirm budget, timing, materials, and address."], ["Attachments", "Share photos and measurements." ]].map(([title, body]) => ({ title, body }))} />; }
export function ClientReviewsView() { return <SimpleDashboardView eyebrow="Trust" title="Reviews" body="Review completed work and help the marketplace reward skilled artisans." stats={[{ label: "Pending", value: 0, subtext: "Reviews", icon: Star }]} items={[["Rate quality", "Share honest feedback after work is complete."], ["Add details", "Mention punctuality, communication, and finish quality."], ["Build trust", "Reviews help other clients choose well." ]].map(([title, body]) => ({ title, body }))} />; }
export function ClientSettingsView() { return <SimpleDashboardView eyebrow="Account" title="Settings" body="Manage profile details, notifications, saved locations, and preferences." stats={[{ label: "Profile", value: "Active", subtext: "Client account", icon: Settings }]} items={[["Personal info", "Keep contact details accurate."], ["Notifications", "Choose message and job alerts."], ["Locations", "Save common project addresses." ]].map(([title, body]) => ({ title, body }))} />; }
